In [ ]:
#Neural Network Building from Scratch, Certain Basics

# Let's suppose that I have three input layers
# The weights represent the 'influence' of the layers on the ouputs
# A simple way to understand what the bias is: 
# It is somehow similar to the constant b of a linear function y = ax + b
# It allows me to move the line up and down to fit the prediction with the data better.
# Without b, the line always goes through the origin (0, 0) and I may get a poorer fit.
# The easiest case!!!

inputs = [1.2, 5.1, 2.1]
weights = [3.1, 2.1, 8.7]
bias = 3
output = sum(inputs[i]*weights[i] for i in range(2)) + bias


In [ ]:
# CODING OF A LAYER
# 4 inputs (in the layer) and 3 outputs
# Trying to predict failure or not for servers (for example)
# So various sensors : heat, humidity, ... (inputs) 
# Different weights that represent different influences of the inputs on each output. 
# Hence weights[j] of len 4 : influence of the 4 inputs on output j
# Each neuron from the ouptut will have its own separate bias

inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

output=[inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
        inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
        inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]


# Inputs are often outputs from other neurons. Imagine that we want to change the output values, then we 
# would have to change the weights and biases. 
# The whole point of Deep Learning : how to tune best these values to do what is expected. 

In [ ]:
# Let's move to a better code

inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

# First version
layer_output_1 = []
for j in range(len(weights)):
    influence = sum(inputs[i]*weights[j][i] for i in range(len(inputs)))
    layer_output_1.append(influence + biases[j])

#Second version 
layer_ouput_2 = []
for neuron_weight, neuron_bias in zip(weights, biases):
    neuron_output = 0
    for input, weight in zip(inputs, neuron_weight):
        neuron_output += input*weight
    neuron_output += neuron_bias
    layer_ouput_2.append(neuron_output)

In [ ]:
# In Numpy, a list is a 1-D array
# Example : lol=[[1,1,1,1], [1,2,3,4]] shape: (2,4) and type : 2D array, matrix 
# lolol = [ [[1,1,1,1],[2,3,5,1]], [[1,1,2,2],[2,3,4,5]], [[2,2,2,2],[9,4,5,6]] ]  shape : (3,2,4)

import numpy as np

inputs1 = [1, 2, 3, 2.5]
weights1 = [0.2, 0.8, -0.5, 1.0]
bias1 = 2
output1 = np.dot(inputs1, weights1) + bias1 # dot : produit scalaire 

inputs2 = [1, 2, 3, 2.5]
weights2 = [[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]
biases2 = [2, 3, 0.5]
output2 = np.dot(weights2, inputs2) + biases2

# Inputs are features from a single sample (describe the current status of an object of interest)
# I want a batch of these samples

inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0], 
           [0.5, -0.91, 0.26, -0.5], 
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

# If I multiply directly by taking the dot, problem of dimensions. I need to transpose.
# What I did previously works only if I have one sample. 
# [2.8  -1.79  1.885]                                [ 4.8  1.21  2.385]
# [6.9  -4.81  -0.3]        +   [2.O  3.0  0.5]   =  [8.9  -1.81  0.2]
# [-0.59 -1.989  -0.474]                                .....

output = np.dot(inputs, np.array(weights).T) + biases

# Add layer

biases = [2, 3, 0.5]
weights_layer = [[0.1, -0.14, 0.5], 
           [-0.5, 0.12, -0.33], 
           [-0.44, -0.73, -0.13]]
biases_layer = [-1, 2, -0.5]

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases
layer2_outputs = np.dot(layer1_outputs, np.array(weights_layer).T) + biases_layer

In [ ]:
import numpy as np

X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

# 0.10 because we want the weights to be small
# format of a matrix so we don't have to transpose. If 4 inputs and 3 layers :
# self.weights returns 4*3 matrix where i,j : weight of input i on neuron j  

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = (0.10) * np.random.randn(n_inputs, n_neurons)                                                       
        self.biases = np.zeros((1, n_neurons)) # The format is always in 'shape': 1 array
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

# Thanks to the definition of the class, Layer_Dense(4,5) create a dense layer with :
# 4 input features and 5 neurons. This creates a weight matrix of shape (4,5). 
# And a bias vector of shape(1,5) 

layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)
layer1.forward(X)
#print(layer1.output)
layer2.forward(layer1.output)
#print(layer2.output)  


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Spiral dataset
#https://cs231n.github.io/neural-networks-case-study/ inspired by this generated data

def create_data(points, classes):
    X = np.zeros((points*classes,2)) # data matrix (each row = single example)
    y = np.zeros(points*classes, dtype='uint8') # class labels
    for class_number in range(classes):
        ix = range(points*class_number, points*(class_number+1))
        r = np.linspace(0.0,1,points) # radius
        t = np.linspace(class_number*4,(class_number+1)*4, points) + np.random.randn(points)*0.2 # theta
        X[ix] = np.c_[r*np.sin(t*2.5), r*np.cos(t*2.5)]
        y[ix] = class_number
    return X, y


X, y = create_data(100,3)
plt.figure(figsize=(8, 6))
plt.scatter(X[:, 0], X[:, 1], c=y, cmap="rainbow", s=20)
plt.xlabel("X1")
plt.ylabel("X2")
plt.title("Synthetic Spiral Data")
plt.show()

![Illustration of the spiral dataset] /Users/noam/Desktop/Code/Spiral-data-BNN.png

In [ ]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

X, y = spiral_data(100, 3)

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = (0.10) * np.random.randn(n_inputs, n_neurons)                                                       
        self.biases = np.zeros((1, n_neurons)) # The format is always in 'shape': 1 array
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


# Activation function
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0,inputs)

layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLU()

layer1.forward(X)
#print(layer1.output)
activation1.forward(layer1.output)
print(activation1.output)


In [ ]:
# We have to train the model (making the error : what is out -
# what is expected as small as possible). 
# Infos sent back to the hidden layers who 'learn'
# To do that, the outputs have to 'make sense' for us
# Softmax activation function : transforms the ouput in probabilities
# Keeps the sense of the ouput : negative values are smaller than positive thanks to the exp
# We normalize so the outputs are now probabilities

import numpy as np

layer_outputs = [4.8, 1.21, 2.385]
# exp_values = [math.exp(x) for x in layer_outputs]
exp_values = np.exp(layer_outputs)
# normalized_value = np.sum(exp_values)
normalized_output = exp_values / np.sum(exp_values)


In [ ]:
# Like previously but with a batch this time to train the model
# axis=1 somme par lignes, axis=0 somme par colonnes
# keepdims allows transposition

import numpy as np

layer_outputs = [[4.8, 1.21, 2.385],
                 [8.9, -1.81, 0.2],
                 [1.41, 1.051, 0.026]]

exp_values = np.exp(layer_outputs)
row_sum = np.sum(layer_outputs, axis=1, keepdims=True)
output = exp_values / row_sum


# Substraction of the max value method
# exp grows significantly and error often associated with big values of exp
# for every output, output - max(ouput) and then exp, end probabilities are the same

import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = (0.10) * np.random.randn(n_inputs, n_neurons)                                                       
        self.biases = np.zeros((1, n_neurons)) 
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

# Activation function
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0,inputs)

# Ici, l'input sera un output puisque on travaille avec des layers
class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

X,y = spiral_data(samples=100, classes=3)

dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3,3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

activation2.output[:5]

In [ ]:
# We need some measure of how wrong the model is : loss function
# Here, softmax classifier with categorical cross-entropy
# One batch

import math
softmax_output = [0.7, 0.1, 0.2] # output out of my activation function after layer
target_output = [1, 0, 0]
loss = -sum(math.log(softmax_output[i])*target_output[i] for i in range(2))

In [ ]:
# Classes : 0-dog, 1-cat, 2-human
# Imagine that the 3 images (3-sample) we test are dog, cat, cat : class_targets = [0, 1, 1]
import numpy as np

y_pred_clipped = [[0.7, 0.1, 0.2],
                   [0.1, 0.5, 0.4],
                   [0.02, 0.9, 0.08]]
y_true = [0, 1, 1]
samples = 3

import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = (0.10) * np.random.randn(n_inputs, n_neurons)                                                       
        self.biases = np.zeros((1, n_neurons)) 
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

# Activation function
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0,inputs)

# Ici, l'input sera un output puisque on travaille avec des layers
class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

class Loss:
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss

# y_pred is what goes out, y_pred is what we whould observe
class Loss_CategoricalCrossEntropy(Loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)
        if len(y_true.shape) ==1:
            correct_confidences = y_pred_clipped[range(samples), y_true]

        # y_pred_clipped = [[0.7, 0.1, 0.2],                [0,    [0,         [0.7,
        #                   [0.1, 0.5, 0.4],   samples = 3   1,  ,  1,   =      0.5,
        #                   [0.02, 0.9, 0.08]]               2]     1]          0.9]

        elif len(y_true.shape) ==2:
            correct_confidences = np.sum(y_pred_clipped*y_true, axis=1)
        negative_log_likelihoods = -np.log(correct_confidences)

        return negative_log_likelihoods

X,y = spiral_data(samples=100, classes=3)

dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3,3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

loss_function = Loss_CategoricalCrossEntropy()
loss = loss_function.calculate(activation2.output, y)
print("Loss:", loss)


In [ ]:
# Simple Neuron Network
# 2 inputs, 1 output : simple classifier to distinguish 2 groups False and True
# If False and True = True.  True and False = False. T and T = T.   F and F = F.
# We translate this situation with 0 for False and 1 for True

import numpy as np

weights = np.random.rand(3)
bias = 1
learning_rate = 1

def Heaviside_activation_function(x):
    if x>0:
        return 1
    else:
        return 0

def Network(input1, input2, output):
    network_pre_output = input1*weights[0] + input2*weights[1] + bias*weights[2]
    network_output = Heaviside_activation_function(network_pre_output)
    error = output - network_output
    weights[0] += error*input1*learning_rate
    weights[1] += error*input2*learning_rate
    weights[2] += error*bias*learning_rate

# Learning phase : tout le but de cette phase va etre d'ajuster les 3 coeffs de weights 

for _ in range(60):
    Network(0, 0, 0)
    Network(1, 1, 1)
    Network(0, 1, 1)
    Network(1, 0, 1)

# Testing function

def testing_Network(input1, input2):
    pre_output = input1*weights[0] + input2*weights[1] +bias*weights[2]
    return Heaviside_activation_function(pre_output)

print("Testing the trained network:")
print(f"Input (0, 0): Output -> {testing_Network(0, 0)}")  
print(f"Input (1, 0): Output -> {testing_Network(1, 0)}")
print(f"Input (0, 1): Output -> {testing_Network(0, 1)}")